version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@octokit/rest"
    versions:
    - 18.0.15
    - 18.1.0
    - 18.1.1
    - 18.2.0
    - 18.2.1
    - 18.3.0
    - 18.3.1
    - 18.3.2
    - 18.3.3
    - 18.3.4
    - 18.3.5
    - 18.4.0
    - 18.5.0
    - 18.5.2
  - dependency-name: auth0-js
    versions:
    - 9.14.3
    - 9.15.0
  - dependency-name: dynamoose
    versions:
    - 2.4.1
    - 2.6.0
    - 2.7.0
    - 2.7.1
    - 2.7.2
  - dependency-name: chai
    versions:
    - 4.2.0
    - 4.3.0
    - 4.3.1
    - 4.3.3
  - dependency-name: config
    versions:
    - 3.3.3
    - 3.3.4
  - dependency-name: nodemailer
    versions:
    - 6.4.17
    - 6.4.18
    - 6.5.0
  - dependency-name: joi
    versions:
    - 17.3.0
  - dependency-name: lodash
    versions:
    - 4.17.20
